### ISSUE TITLE
Vertical Spacing (layout down Y instead of Z)

### ISSUE THREAD

**Issue by mwomp** [boner-cmd/asset-spacer#15]
Vertical Spacing (layout down Y instead of Z)

Useful for displaying screenspace of straight-on assets

**Comment by boner-cmd** [comment]
Current code lays objects out from the origin, which is simplest- would that be okay? (items at beginning of pack would be in row starting at y = 0, then progressing up y axis). Or is top-down sequence a requirement? Both are doable, the latter is just a little more involved.

**Comment by boner-cmd** [comment]
Or is top-down sequence a requirement?

**Comment by mwomp** [comment]
No preference, whatever is least effort
